# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleAws' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CryptoSwift'

  # Pods for SampleAws

  target 'SampleAwsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAwsUITests' do
    # Pods for testing
  end

end
